#!/usr/bin/ruby
# -*- encoding : utf-8 -*-

require 'yaml'
require "docopt"
require 'pp'

require_relative 'oo_reader'
require_relative 'txt_reader'
require_relative 'comptes'
require_relative 'depenses'

doc = <<DOCOPT
Usage: #{__FILE__} <input_file>  [-c <config_file>]

Options:
  -c --config   Config file to use

Input file can be OpenOffice Spreadsheet file (.ods), or text file (.txt).
See examples for more about format.
DOCOPT

begin
  docopt = Docopt::docopt(doc)
rescue Docopt::Exit => e
  puts e.message
  exit 1
end


# Test file existence
input_file = docopt['<input_file>']
unless File.exists?(input_file)
  puts "#{input_file} doesn't exists"
  exit 1
end

# Open config
config_file = docopt['--config'] ? docopt['<config_file>'] : 'config.yml'
conf = YAML.load_file(config_file)

# Solving
if input_file.end_with?('.ods')
  o = OoReader.new(input_file, conf)
elsif input_file.end_with?('.txt')
  o = TxtReader.new(input_file, conf)
else
  puts "#{input_file}: unknown file extension. Must be '.txt' or '.ods'."
  exit 2
end

Comptes.affichage_probleme(o)

resultat = Comptes.calcul_dettes(o, conf['transfers_priorities_order'])

puts
puts
puts "Résultat :"
puts
puts resultat

puts
puts
puts "Vérification :"
Comptes.affichage_verification_resultat(o, resultat)
